export const FAKE_POPULARS = [
  {
    backdrop_path: "/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg",
    first_air_date: "2005-01-03",
    genre_ids: [35, 10767],
    id: 14981,
    name: "The Late Late Show with Craig Ferguson",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Late Late Show with Craig Ferguson",
    overview:
      "The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n\nSince becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.",
    popularity: 11809.245,
    poster_path: "/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg",
    vote_average: 7.1,
    vote_count: 76,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/9In9QgVJx7PlFOAgVHCKKSbo605.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 739.045,
    first_air_date: "2013-12-02",
    vote_average: 8.7,
    vote_count: 8550,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pMCvRynXABgLBMKHYa2UXjTBMsU.jpg",
    id: 615,
    name: "Futurama",
    original_language: "en",
    original_name: "Futurama",
    overview:
      "The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery company in the retro-futuristic 31st century.",
    poster_path: "/7RRHbCUtAsVmKI6FEMzZB6Re88P.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765],
    popularity: 656.607,
    first_air_date: "1999-03-28",
    vote_average: 8.396,
    vote_count: 2852,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/j5w04XEuFv85N3RIovXBJIHxjSb.jpg",
    id: 1920,
    name: "Twin Peaks",
    original_language: "en",
    original_name: "Twin Peaks",
    overview:
      "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately leads him deep into the heart of the surrounding woodland and his very own soul.",
    poster_path: "/lA9CNSdo50iQPZ8A2fyVpMvJZAf.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 88.579,
    first_air_date: "1990-04-08",
    vote_average: 8.3,
    vote_count: 1761,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/a906PH7CDmSOdS7kmnAgdWk5mhv.jpg",
    id: 67744,
    name: "Mindhunter",
    original_language: "en",
    original_name: "Mindhunter",
    overview:
      "An agent in the FBI's Elite Serial Crime Unit develops profiling techniques as he pursues notorious serial killers and rapists.",
    poster_path: "/fbKE87mojpIETWepSbD5Qt741fp.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 49.038,
    first_air_date: "2017-10-13",
    vote_average: 8.069,
    vote_count: 2076,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zP5SftyPx2VCdly369kTVVNIcT3.jpg",
    id: 1404,
    name: "Chuck",
    original_language: "en",
    original_name: "Chuck",
    overview:
      "When Buy More computer geek Chuck Bartowski unwittingly downloads a database of government information and deadly fighting skills into his head, he becomes the CIA's most vital secret. This sets Chuck on a path to become a full-fledged spy.",
    poster_path: "/vEZvGVVMjk1TRs59nfypTI5lAXj.jpg",
    media_type: "tv",
    genre_ids: [10759, 35, 18],
    popularity: 101.26,
    first_air_date: "2007-09-24",
    vote_average: 7.741,
    vote_count: 873,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/8PtOfFfX3anE4T63NjnfULRalMq.jpg",
    id: 186,
    name: "Weeds",
    original_language: "en",
    original_name: "Weeds",
    overview:
      "After the unexpected death of her husband, a suburban mom resorts to selling weed to support her family.",
    poster_path: "/gKUsBTa5b0GY7U4iWBseeBalfjO.jpg",
    media_type: "tv",
    genre_ids: [35, 80, 18],
    popularity: 61.422,
    first_air_date: "2005-08-07",
    vote_average: 7.46,
    vote_count: 743,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mlAzs3tyl5253roHi6eIRbeuONN.jpg",
    id: 1400,
    name: "Seinfeld",
    original_language: "en",
    original_name: "Seinfeld",
    overview:
      "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
    poster_path: "/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 392.725,
    first_air_date: "1989-07-05",
    vote_average: 8.283,
    vote_count: 1647,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qCXY93t7QnKp6aWT1WKaQo0Qt5r.jpg",
    id: 4589,
    name: "Arrested Development",
    original_language: "en",
    original_name: "Arrested Development",
    overview:
      "The story of a wealthy family that lost everything, and the one son who had no choice but to keep them all together.",
    poster_path: "/qMzwO952hMWQSCfHkp7IL20s4K7.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 128.836,
    first_air_date: "2003-11-02",
    vote_average: 7.977,
    vote_count: 1165,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rFdBQdtOoeIVzmXbzSZEo0GIqoE.jpg",
    id: 96580,
    name: "Resident Alien",
    original_language: "en",
    original_name: "Resident Alien",
    overview:
      "Crash-landed alien Harry takes on the identity of a small-town Colorado doctor. Arriving with a secret mission, he starts off living a simple life…but things get a bit rocky when he’s roped into solving a local murder and realizes he needs to assimilate into his new world. As he does, he begins to wrestle with the moral dilemma of his mission and asking the big life questions like: “Are human beings worth saving?” and “Why do they fold their pizza before eating it?”",
    poster_path: "/uJMbW9d1QqoJWmGOqJv8mAbegac.jpg",
    media_type: "tv",
    genre_ids: [10765],
    popularity: 70.019,
    first_air_date: "2021-01-27",
    vote_average: 7.988,
    vote_count: 560,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pXpK8GnLL0wZkfelg5lCVSOnytN.jpg",
    id: 1950,
    name: "Everwood",
    original_language: "en",
    original_name: "Everwood",
    overview:
      "After the death of his wife, world-class neurosurgeon Dr. Andrew Brown leaves Manhattan and moves his family to the small town of Everwood, Colorado. There he becomes a small-town doctor and learns parenting on the fly as he raises his talented but resentful 15-year-old son Ephram and his 9-year-old daughter Delia.",
    poster_path: "/4zmuA2Ql1QdUtw9OM6MdmtXnZEF.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 238.543,
    first_air_date: "2002-09-16",
    vote_average: 7.629,
    vote_count: 163,
    origin_country: ["US"],
  },
];
